server:
  port: 9090
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
    eureka-service-url-poll-interval-seconds: 3

spring:
  application:
    name: zuul-gateway
ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000
